
package artifact;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "webservice", targetNamespace = "http://webser/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Webservice {


    /**
     * 
     * @return
     *     returns java.util.List<artifact.Publicationoficial>
     */
    @WebMethod(operationName = "getfull_list")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getfull_list", targetNamespace = "http://webser/", className = "artifact.GetfullList")
    @ResponseWrapper(localName = "getfull_listResponse", targetNamespace = "http://webser/", className = "artifact.GetfullListResponse")
    public List<Publicationoficial> getfullList();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<artifact.Publicationoficial>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getordenas", targetNamespace = "http://webser/", className = "artifact.Getordenas")
    @ResponseWrapper(localName = "getordenasResponse", targetNamespace = "http://webser/", className = "artifact.GetordenasResponse")
    public List<Publicationoficial> getordenas(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns artifact.Publicationoficial
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getsingle", targetNamespace = "http://webser/", className = "artifact.Getsingle")
    @ResponseWrapper(localName = "getsingleResponse", targetNamespace = "http://webser/", className = "artifact.GetsingleResponse")
    public Publicationoficial getsingle(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(operationName = "gettitle_list")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "gettitle_list", targetNamespace = "http://webser/", className = "artifact.GettitleList")
    @ResponseWrapper(localName = "gettitle_listResponse", targetNamespace = "http://webser/", className = "artifact.GettitleListResponse")
    public List<String> gettitleList();

}
